name: Example Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Wait for Server to Start
      run: sleep 3
      
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and run Docker container
      run: |
        python3 -m http.server
        docker build -t mycontainer .
        docker run -v $(pwd)/output:/output mycontainer
